import { useState, useEffect } from 'react';
import { db } from '../../lib/firebase';
import { collection, query, orderBy, getDocs, doc, deleteDoc } from 'firebase/firestore';
import { Eye, Download, Search, FileText, Trash2, Calendar, Lock } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { downloadFileFromFirestore } from '../../lib/fileStorage';

interface JobApplication {
    id: string;
    firstName: string;
    lastName: string;
    email: string;
    phone: string;
    linkedIn: string;
    coverLetter: string;
    jobTitle: string;
    hasFile?: boolean;
    fileName?: string;
    createdAt: any;
}

const JobApplicationsTable = () => {
    const [applications, setApplications] = useState<JobApplication[]>([]);
    const [loading, setLoading] = useState(true);
    const [searchTerm, setSearchTerm] = useState('');
    const [selectedApp, setSelectedApp] = useState<JobApplication | null>(null);

    // Delete Modal State
    const [showDeleteModal, setShowDeleteModal] = useState(false);
    const [appToDelete, setAppToDelete] = useState<string | null>(null);
    const [deletePassword, setDeletePassword] = useState('');
    const [deleteError, setDeleteError] = useState('');
    const [isDeleting, setIsDeleting] = useState(false);

    useEffect(() => {
        fetchApplications();
    }, []);

    const fetchApplications = async () => {
        setLoading(true);
        try {
            const q = query(collection(db, "job_applications"), orderBy("createdAt", "desc"));
            const querySnapshot = await getDocs(q);
            const apps: JobApplication[] = [];
            querySnapshot.forEach((doc) => {
                apps.push({ id: doc.id, ...doc.data() } as JobApplication);
            });
            setApplications(apps);
        } catch (error) {
            console.error("Error fetching job applications: ", error);
        } finally {
            setLoading(false);
        }
    };

    const formatDate = (timestamp: any) => {
        if (!timestamp) return 'N/A';
        const date = timestamp.toDate();
        return new Intl.DateTimeFormat('en-US', {
            year: 'numeric',
            month: 'short',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit'
        }).format(date);
    };

    const generatePDF = (app: JobApplication) => {
        const doc = new jsPDF();

        // Header
        doc.setFontSize(22);
        doc.setTextColor(37, 99, 235); // Primary blue
        doc.text("Job Application", 105, 20, { align: "center" });

        doc.setFontSize(14);
        doc.setTextColor(100, 116, 139); // Slate 500
        doc.text(`Applicant: ${app.firstName} ${app.lastName}`, 105, 30, { align: "center" });
        doc.text(`Position: ${app.jobTitle}`, 105, 38, { align: "center" });

        // Line separator
        doc.setDrawColor(226, 232, 240);
        doc.setLineWidth(0.5);
        doc.line(20, 45, 190, 45);

        // Details Table
        autoTable(doc, {
            startY: 55,
            head: [['Field', 'Details']],
            body: [
                ['Submitted', formatDate(app.createdAt)],
                ['Email', app.email],
                ['Phone', app.phone],
                ['LinkedIn', app.linkedIn || 'N/A'],
                ['Resume Attached', app.hasFile ? 'Yes' : 'No'],
            ],
            theme: 'grid',
            headStyles: { fillColor: [37, 99, 235], textColor: 255, fontStyle: 'bold' },
            bodyStyles: { textColor: 50 },
            columnStyles: { 0: { fontStyle: 'bold', cellWidth: 50 } }
        });

        // Cover Letter
        const finalY = (doc as any).lastAutoTable.finalY || 130;
        doc.setFontSize(14);
        doc.setTextColor(15, 23, 42);
        doc.text("Cover Letter", 20, finalY + 15);

        doc.setFontSize(10);
        doc.setTextColor(50);
        const splitPitch = doc.splitTextToSize(app.coverLetter || "No cover letter provided.", 170);
        doc.text(splitPitch, 20, finalY + 25);

        // Footer
        const pageCount = (doc.internal as any).getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(150);
            doc.text(`Generated by Ryleni Admin Dashboard - Page ${i} of ${pageCount}`, 105, 290, { align: "center" });
        }

        return doc;
    };

    const handleDownloadIndividualPDF = (app: JobApplication) => {
        const doc = generatePDF(app);
        const safeName = `${app.firstName.replace(/[^a-z0-9]/gi, '_')}_${app.lastName.replace(/[^a-z0-9]/gi, '_')}`;
        doc.save(`JobApp_${safeName}.pdf`);
    };

    const handleDownloadResume = async (appId: string, fileName: string) => {
        try {
            await downloadFileFromFirestore(appId, fileName, "job_applications");
        } catch (error) {
            alert('Failed to download resume. It may have been removed.');
        }
    };


    const handleExportCSV = () => {
        const headers = ['Date', 'First Name', 'Last Name', 'Email', 'Phone', 'LinkedIn', 'Position', 'Has Resume'];
        const csvContent = [
            headers.join(','),
            ...applications.map(app => [
                `"${formatDate(app.createdAt)}"`,
                `"${app.firstName}"`,
                `"${app.lastName}"`,
                `"${app.email}"`,
                `"${app.phone}"`,
                `"${app.linkedIn || ''}"`,
                `"${app.jobTitle}"`,
                `"${app.hasFile ? 'Yes' : 'No'}"`
            ].join(','))
        ].join('\n');

        const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
        const link = document.createElement('a');
        link.href = URL.createObjectURL(blob);
        link.download = `ryleni_job_applications_${new Date().toISOString().split('T')[0]}.csv`;
        link.click();
    };

    const confirmDelete = (id: string, e: React.MouseEvent) => {
        e.stopPropagation();
        setAppToDelete(id);
        setDeletePassword('');
        setDeleteError('');
        setShowDeleteModal(true);
    };

    const handleDelete = async () => {
        if (!appToDelete) return;

        if (deletePassword !== 'reldel987') {
            setDeleteError('Incorrect administrator password');
            return;
        }

        setIsDeleting(true);
        setDeleteError('');

        try {
            await deleteDoc(doc(db, "job_applications", appToDelete));
            setApplications(applications.filter(app => app.id !== appToDelete));
            setShowDeleteModal(false);
            if (selectedApp?.id === appToDelete) {
                setSelectedApp(null);
            }
        } catch (error) {
            console.error("Error deleting application: ", error);
            setDeleteError("Failed to delete application. Please try again.");
        } finally {
            setIsDeleting(false);
            setAppToDelete(null);
            setDeletePassword('');
        }
    };


    const filteredApps = applications.filter(app => {
        const searchString = `${app.firstName} ${app.lastName} ${app.email} ${app.jobTitle}`.toLowerCase();
        return searchString.includes(searchTerm.toLowerCase());
    });

    if (loading) {
        return (
            <div className="flex justify-center items-center h-64">
                <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
            </div>
        );
    }

    return (
        <div className="space-y-6">
            {/* Header Actions */}
            <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 bg-white p-4 rounded-xl shadow-sm border border-gray-100">
                <div>
                    <h2 className="text-xl font-bold text-gray-900 mb-1">Job Applications</h2>
                    <span className="text-sm font-medium text-gray-500 bg-gray-100 px-2 py-0.5 rounded w-fit inline-flex items-center gap-1.5">
                        Total Responses: <span className="text-gray-900 font-bold">{applications.length}</span>
                    </span>
                </div>

                <div className="flex flex-wrap items-center gap-3 w-full sm:w-auto">
                    <div className="relative flex-1 sm:min-w-[250px]">
                        <input
                            type="text"
                            placeholder="Search applicants..."
                            value={searchTerm}
                            onChange={(e) => setSearchTerm(e.target.value)}
                            className="w-full pl-10 pr-4 py-2 border border-gray-200 rounded-lg focus:ring-2 focus:ring-primary/20 focus:border-primary outline-none transition-all text-sm"
                        />
                        <Search className="w-4 h-4 text-gray-400 absolute left-3 top-1/2 -translate-y-1/2" />
                    </div>

                    <button
                        onClick={handleExportCSV}
                        className="flex items-center gap-2 bg-white border border-gray-200 text-gray-700 px-4 py-2 rounded-lg text-sm font-medium hover:bg-gray-50 transition-colors shadow-sm"
                    >
                        <Download className="w-4 h-4" />
                        Export CSV
                    </button>
                </div>
            </div>

            {/* Table */}
            <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
                <div className="overflow-x-auto">
                    <table className="w-full text-left border-collapse">
                        <thead>
                            <tr className="bg-gray-50/50 border-b border-gray-100/80 text-xs uppercase tracking-wider text-gray-500">
                                <th className="p-4 font-semibold">Applicant</th>
                                <th className="p-4 font-semibold">Position</th>
                                <th className="p-4 font-semibold">Contact</th>
                                <th className="p-4 font-semibold">Date</th>
                                <th className="p-4 font-semibold">Resume</th>
                                <th className="p-4 font-semibold text-right">Actions</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-gray-50 text-sm">
                            {filteredApps.length === 0 ? (
                                <tr>
                                    <td colSpan={6} className="p-8 text-center text-gray-500">
                                        No applications found matching your search.
                                    </td>
                                </tr>
                            ) : (
                                filteredApps.map((app) => (
                                    <tr
                                        key={app.id}
                                        onClick={() => setSelectedApp(app)}
                                        className="hover:bg-blue-50/30 transition-colors cursor-pointer group"
                                    >
                                        <td className="p-4">
                                            <div className="font-medium text-gray-900">{app.firstName} {app.lastName}</div>
                                            <div className="text-xs text-gray-500 mt-0.5 max-w-[200px] truncate">
                                                ID: {app.id.substring(0, 8)}
                                            </div>
                                        </td>
                                        <td className="p-4 text-gray-700 font-medium">
                                            {app.jobTitle}
                                        </td>
                                        <td className="p-4">
                                            <div className="text-gray-900">{app.email}</div>
                                            <div className="text-gray-500 text-xs mt-0.5">{app.phone}</div>
                                        </td>
                                        <td className="p-4">
                                            <div className="inline-flex items-center gap-1.5 text-gray-600 bg-gray-50 px-2.5 py-1 rounded-md text-xs font-medium border border-gray-100">
                                                <Calendar className="w-3 h-3" />
                                                {formatDate(app.createdAt)}
                                            </div>
                                        </td>
                                        <td className="p-4">
                                            {app.hasFile ? (
                                                <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium bg-green-100 text-green-700">
                                                    <FileText className="w-3.5 h-3.5" />
                                                    Attached
                                                </span>
                                            ) : (
                                                <span className="text-gray-400 text-xs italic">No file</span>
                                            )}
                                        </td>
                                        <td className="p-4 text-right">
                                            <div className="flex items-center justify-end gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                                                <button
                                                    onClick={(e) => { e.stopPropagation(); setSelectedApp(app); }}
                                                    className="p-1.5 text-blue-600 hover:bg-blue-50 rounded"
                                                    title="View Details"
                                                >
                                                    <Eye className="w-4 h-4" />
                                                </button>
                                                <button
                                                    onClick={(e) => { e.stopPropagation(); handleDownloadIndividualPDF(app); }}
                                                    className="p-1.5 text-green-600 hover:bg-green-50 rounded"
                                                    title="Download Profile PDF"
                                                >
                                                    <Download className="w-4 h-4" />
                                                </button>
                                                {app.hasFile && app.fileName && (
                                                    <button
                                                        onClick={(e) => { e.stopPropagation(); handleDownloadResume(app.id, app.fileName!); }}
                                                        className="p-1.5 text-purple-600 hover:bg-purple-50 rounded"
                                                        title="Download Resume"
                                                    >
                                                        <FileText className="w-4 h-4" />
                                                    </button>
                                                )}
                                                <button
                                                    onClick={(e) => confirmDelete(app.id, e)}
                                                    className="p-1.5 text-red-600 hover:bg-red-50 rounded"
                                                    title="Delete Application"
                                                >
                                                    <Trash2 className="w-4 h-4" />
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                ))
                            )}
                        </tbody>
                    </table>
                </div>
            </div>

            {/* Detail Modal */}
            <AnimatePresence>
                {selectedApp && (
                    <motion.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-gray-900/60 backdrop-blur-sm"
                        onClick={() => setSelectedApp(null)}
                    >
                        <motion.div
                            initial={{ y: 20, opacity: 0, scale: 0.95 }}
                            animate={{ y: 0, opacity: 1, scale: 1 }}
                            exit={{ y: 20, opacity: 0, scale: 0.95 }}
                            onClick={(e) => e.stopPropagation()}
                            className="bg-white rounded-2xl shadow-xl w-full max-w-3xl max-h-[90vh] flex flex-col overflow-hidden border border-gray-100"
                        >
                            {/* Modal Header */}
                            <div className="p-6 border-b border-gray-100 flex justify-between items-start bg-gray-50/50">
                                <div>
                                    <div className="flex items-center gap-3 mb-1">
                                        <h3 className="text-2xl font-bold text-gray-900">
                                            {selectedApp.firstName} {selectedApp.lastName}
                                        </h3>
                                    </div>
                                    <p className="text-primary font-medium">{selectedApp.jobTitle}</p>
                                    <p className="text-sm text-gray-500 mt-2 flex items-center gap-1.5">
                                        <Calendar className="w-4 h-4" />
                                        Applied: {formatDate(selectedApp.createdAt)}
                                    </p>
                                </div>
                                <button
                                    onClick={() => setSelectedApp(null)}
                                    className="p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-full transition-colors"
                                >
                                    ✕
                                </button>
                            </div>

                            {/* Modal Body */}
                            <div className="p-6 overflow-y-auto custom-scrollbar flex-1">
                                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                                    {/* Column 1 */}
                                    <div className="space-y-6">
                                        <div>
                                            <h4 className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-3">Contact Information</h4>
                                            <div className="space-y-3 bg-gray-50 p-4 rounded-xl border border-gray-100">
                                                <div>
                                                    <span className="text-sm text-gray-500 block mb-0.5">Email</span>
                                                    <a href={`mailto:${selectedApp.email}`} className="text-sm font-medium text-gray-900 hover:text-primary transition-colors">{selectedApp.email}</a>
                                                </div>
                                                <div>
                                                    <span className="text-sm text-gray-500 block mb-0.5">Phone</span>
                                                    <a href={`tel:${selectedApp.phone}`} className="text-sm font-medium text-gray-900 hover:text-primary transition-colors">{selectedApp.phone}</a>
                                                </div>
                                                <div>
                                                    <span className="text-sm text-gray-500 block mb-0.5">LinkedIn</span>
                                                    {selectedApp.linkedIn ? (
                                                        <a href={selectedApp.linkedIn} target="_blank" rel="noreferrer" className="text-sm font-medium text-primary hover:underline">{selectedApp.linkedIn}</a>
                                                    ) : (
                                                        <span className="text-sm text-gray-900">Not provided</span>
                                                    )}
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    {/* Column 2 */}
                                    <div className="space-y-6">
                                        <div>
                                            <h4 className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-3">Documents</h4>
                                            <div className="bg-blue-50/50 p-4 rounded-xl border border-blue-100 flex flex-col gap-3">
                                                {selectedApp.hasFile ? (
                                                    <button
                                                        onClick={(e) => { e.stopPropagation(); handleDownloadResume(selectedApp.id, selectedApp.fileName!); }}
                                                        className="flex items-center gap-2 text-sm font-medium text-primary hover:underline"
                                                    >
                                                        <FileText className="w-4 h-4" />
                                                        Download Resume ({selectedApp.fileName})
                                                    </button>
                                                ) : (
                                                    <div className="text-sm text-gray-500 italic">No resume attached</div>
                                                )}
                                            </div>
                                        </div>
                                    </div>

                                    {/* Full Width */}
                                    <div className="col-span-1 md:col-span-2 space-y-3 pt-4 border-t border-gray-100">
                                        <h4 className="text-xs font-bold text-gray-400 uppercase tracking-wider">Cover Letter</h4>
                                        <div className="bg-gray-50 p-5 rounded-xl border border-gray-100">
                                            <p className="text-sm text-gray-800 whitespace-pre-wrap leading-relaxed font-serif">
                                                {selectedApp.coverLetter || "No cover letter provided."}
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            {/* Modal Footer */}
                            <div className="p-4 border-t border-gray-100 bg-gray-50 flex justify-between items-center rounded-b-2xl">
                                <button
                                    onClick={(e) => confirmDelete(selectedApp.id, e)}
                                    className="px-4 py-2 text-sm font-medium text-red-600 hover:bg-red-50 rounded-lg transition-colors flex items-center gap-2"
                                >
                                    <Trash2 className="w-4 h-4" />
                                    Delete
                                </button>
                                <div className="flex gap-3">
                                    <button
                                        onClick={() => handleDownloadIndividualPDF(selectedApp)}
                                        className="px-5 py-2.5 bg-blue-100 text-blue-700 hover:bg-blue-200 rounded-xl font-medium text-sm transition-colors flex items-center gap-2"
                                    >
                                        <Download className="w-4 h-4" />
                                        Save Profile As PDF
                                    </button>
                                </div>
                            </div>
                        </motion.div>
                    </motion.div>
                )}
            </AnimatePresence>

            {/* Delete Confirmation Modal */}
            <AnimatePresence>
                {showDeleteModal && (
                    <motion.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        className="fixed inset-0 z-[60] flex items-center justify-center p-4 bg-gray-900/60 backdrop-blur-sm"
                        onClick={() => setShowDeleteModal(false)}
                    >
                        <motion.div
                            initial={{ y: 20, opacity: 0, scale: 0.95 }}
                            animate={{ y: 0, opacity: 1, scale: 1 }}
                            exit={{ y: 20, opacity: 0, scale: 0.95 }}
                            onClick={(e) => e.stopPropagation()}
                            className="bg-white rounded-2xl shadow-xl w-full max-w-md overflow-hidden border border-red-100"
                        >
                            <div className="p-6">
                                <div className="w-12 h-12 rounded-full bg-red-100 flex items-center justify-center mb-4 text-red-600">
                                    <Trash2 className="w-6 h-6" />
                                </div>
                                <h3 className="text-xl font-bold text-gray-900 mb-2">Delete Application</h3>
                                <p className="text-sm text-gray-600 mb-6">
                                    This action cannot be undone. This will permanently delete the application data from the database. Please enter the admin password to confirm.
                                </p>

                                <div className="space-y-4">
                                    <div className="relative">
                                        <Lock className="w-5 h-5 text-gray-400 absolute left-3 top-1/2 -translate-y-1/2" />
                                        <input
                                            type="password"
                                            placeholder="Admin Password"
                                            value={deletePassword}
                                            onChange={(e) => setDeletePassword(e.target.value)}
                                            className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-red-500/20 focus:border-red-500 outline-none text-sm transition-all"
                                            autoFocus
                                            onKeyDown={(e) => {
                                                if (e.key === 'Enter') handleDelete();
                                            }}
                                        />
                                    </div>
                                    {deleteError && (
                                        <p className="text-red-500 text-sm">{deleteError}</p>
                                    )}
                                </div>
                            </div>
                            <div className="p-4 bg-gray-50 flex justify-end gap-3 border-t border-gray-100">
                                <button
                                    onClick={() => setShowDeleteModal(false)}
                                    className="px-4 py-2 text-sm font-medium text-gray-600 hover:bg-gray-200 rounded-lg transition-colors"
                                    disabled={isDeleting}
                                >
                                    Cancel
                                </button>
                                <button
                                    onClick={handleDelete}
                                    disabled={isDeleting || !deletePassword}
                                    className="px-4 py-2 text-sm font-medium text-white bg-red-600 hover:bg-red-700 rounded-lg transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
                                >
                                    {isDeleting ? (
                                        <>
                                            <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                                            Deleting...
                                        </>
                                    ) : (
                                        'Permanently Delete'
                                    )}
                                </button>
                            </div>
                        </motion.div>
                    </motion.div>
                )}
            </AnimatePresence>
        </div>
    );
};

export default JobApplicationsTable;
